pipelinestages:
    - name: preprocess
      resourcetype: CPU
    - name: segmentation
      resourcetype: GPU
    - name: extractsurfacemesh
      resourcetype: CPU
    - name: registerimagetoatlas
      resourcetype: GPU
    - name: warpmesh
      resourcetype: CPU
    - name: evalregistration
      resourcetype: CPU
    - name: setatlas2dmap
      resourcetype: CPU
    - name: computeatlas2dmap
      resourcetype: CPU
    - name: projectthicknesstoatlas
      resourcetype: CPU
    - name: projectthicknessto2d
      resourcetype: CPU
